version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: nextjs
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env.development
